version: '3.8'
services:
  mysql:
    image: mysql:oracle
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks: 
  default:
    external:
      name: traefik
