version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks: 
  default:
    external:
      name: traefik
